# Generated by Django 5.2.6 on 2025-11-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('MEMBRO', 'Membro da Banda'), ('VISITANTE', 'Visitante')], default='VISITANTE', max_length=10),
        ),
    ]
