# Generated by Django 5.2.6 on 2025-11-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('ADMIN', 'Super Admin'), ('GESTOR', 'Gestor'), ('PROFESSOR', 'Professor'), ('MEMBRO', 'Membro da Banda'), ('VISITANTE', 'Visitante')], default='VISITANTE', max_length=10),
        ),
    ]
