# Generated by Django 5.2.6 on 2025-11-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usuario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Público?'),
        ),
        migrations.AddField(
            model_name='evento',
            name='pending_approval',
            field=models.BooleanField(default=True, verbose_name='Pendente de Aprovação?'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Público?'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='pending_approval',
            field=models.BooleanField(default=True, verbose_name='Pendente de Aprovação?'),
        ),
    ]
