# Generated by Django 5.2.6 on 2025-12-01 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_evento_is_public_evento_pending_approval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Edital de Seleção', max_length=200)),
                ('conteudo', models.TextField()),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='editais/')),
                ('data_abertura', models.DateTimeField()),
                ('data_fechamento', models.DateTimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('video_demonstracao', models.URLField(blank=True, null=True)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado')], default='PENDENTE', max_length=20)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='core.edital')),
            ],
        ),
    ]
